### ISSUE TITLE
auipc instruction broken

### ISSUE THREAD

**Issue by markusdd** [ataradov/riscv#3]
Hi!

I have played with the core a little more and I have discovered that the AUIPC instruction seems to miscalculate its target address because it takes a register value instead of the PC.

I discovered this while compiling a bit more elaborate application which uses this. I have not seen this instruction being built in by the compiler with your test code, which might by why that issue slipped through.

I was working on a fix and one way to do it might be: to change one assignment in the instrcution decode pipe (line 562):

`id_ra_value_r <= auipc_w ? if_pc_r : reg_r[id_ra_index_w];`

What do you think?

**Comment by ataradov** [comment]
Thanks for reporting this. Is there a simplified C code that makes the compiler issue this instruction? I want to come up with a test. If not, I'll need to create a test case in assembly.

It look like a better way is to use the value jump_addr_w, which in case of AUIPC will be equal to the required result. This way case (id_alu_op_r) can be extended with one more operation ALU_AUIPC, which would be selected in id_alu_op_w assignment.

This will move the multiplexer out of the ID stage into the EX stage, and that adder is there already doing nothing for this instruction.

I will experiment with this later today, and see which version gives better results in terms of speed and resource utilization.

**Comment by markusdd** [comment]
Man you're quick ;)

I came across this by accident, but as it happended when I pulled some functions in from a quite extensive library, I'm afraid I do not really have a 'minimal' example currently.
Anyway this instruction is rather rare it seems, so probably the easiest way is to really put in some inline assembler code.

I would need to do some digging as well to find out when the compiler is inclined to use this instruction.

I also very much like the idea of postponing the calculation into the ex stage, absolutely makes sense.

**Comment by ataradov** [comment]
I've pushed the fix. Inline assembly is  ugly, but at least it works.

**Comment by markusdd** [comment]
Hi,

thank you very much, I think your solution in the execute stage is pretty elegant, makes use of existing resources without introducing more logic depth in the decode stage.

I incorporated your change and it works perfectly.

From my point of view this issue can be closed. (and the first one with the non-clocking assignments as well from a few weeks ago)
